export const ansattedata = [
  { name: "Asbjørn", start: 1, end: 12, hasImage: false },
  { name: "Tore", start: 13, end: 24, hasImage: false },
  { name: "Terese", start: 25, end: 30, hasImage: false },
  { name: "Kirsti", start: 31, end: 33, hasImage: false },
  { name: "Mari KK", start: 67, end: 84, hasImage: false },
  { name: "Harald", start: 85, end: 98, hasImage: false },
  { name: "Otto A", start: 99, end: 108, hasImage: false },
  { name: "Mira", start: 109, end: 112, hasImage: false },
  { name: "Vegar P", start: 159, end: 161, hasImage: false },
  { name: "Tore", start: 162, end: 174, hasImage: false },
  { name: "Vegar K", start: 175, end: 179, hasImage: false },
  { name: "Mira", start: 180, end: 187, hasImage: false },
  { name: "Svein", start: 186, end: 197, hasImage: false },
  { name: "Åsne", start: 198, end: 204, hasImage: false },
  { name: "Live", start: 263, end: 274, hasImage: false },
  { name: "Tobias", start: 276, end: 287, hasImage: false },
  { name: "Heidi", start: 288, end: 305, hasImage: false },
  { name: "Trude", start: 294, end: 310, hasImage: false },
  { name: "Tobias", start: 312, end: 312, hasImage: false },
]
